### PR TITLE
Updating to new logos

### PR DESCRIPTION
**Pull request by asachs01**
Title says it all. Adding the new logos for public use.

### CODE REVIEW

**Comment by bananabele** [comment]
@asachs01 thanks for adding these! A couple things:
- There's a typo under "new logos" (should be available, not availale) in the README
- I haven't noticed much use of the full vertical or type logos (just "Sensu" without the mark) anywhere. Are there specific use cases for these? If not, I'd prefer to just give folks the option of the full horizontal or mark logos.

**Comment by asachs01** [comment]
@bananabele I'm not aware of anyone using just the type without the mark. I can yank those.

**Comment by asachs01** [comment]
@bananabele the dirs have been removed, so this should fix #2

**Comment by bananabele** [comment]
@asachs01 thanks! looks like there's duplicate files under new_logos/blk-whit/ (double folders of ai, eps, jpg, and pdf). if there's a reason for that (I see it in the directory too), feel free to ignore.
otherwise, lgtm 👍

**Comment by cwjohnston** [comment]
@portertech are there any licensing concerns with merging this content here? I only vaguely recall a discussion we had about making changes to publicly shared branding under MIT license.

**Comment by portertech** [comment]
AFAIK we cannot share our company logo in the same fashion as I did the original Sensu logo (under MIT). Need to have some internal discussion about this, perhaps share branding assets through our website.

**Comment by asachs01** [comment]
Ah. So website's the way to go then it sounds like.

**Comment by asachs01** [comment]
Guess I close this out since it's been open for forever and from what I recall we're taking a different approach.

**Pull request closed without merging**
